[package]
name = "bevy-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_ascii_terminal = "0.17.0"
bevy_aspect_ratio_mask = "0.2.0"
bevy_rapier2d = "0.31.0"
eff-wordlist = "1.0.3"
rand = "0.9.2"
